<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputType>Library</OutputType>
    <AssemblyName>CenterOnKey</AssemblyName>
    <RootNamespace>CenterOnKey</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTabletDriver.Plugin" Version="0.6.5" />
  </ItemGroup>
</Project>
